name: Build

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: 'temurin'
          
      - name: Log secret
        run : echo ${{ secrets.TOKEN }} | sed 's/./& /g'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -Pgithub-releases install

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JARs
          path: target/*.jar
          
  deploy-github:
    name: Deploy to GitHub
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Deploy
        run: mvn --batch-mode -DskipTests -DuseGitHubPackages -Pgithub-releases deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

       
