name: Build

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          
      - name: Log secret
        run : echo ${{ secrets.TOKEN }} | sed 's/./& /g'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn --batch-mode  install
          
  deploy-github:
    name: Deploy to GitHub2
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          server-id: github

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
          
      - name: Delete previous build if present
        uses: actions/delete-package-versions@v3
        with: 
          owner: 'Balvinder471'
          repo: 'spring5-jokes-app-v2'
          package-name: 'blogzy'
          token: ${{ secrets.TOKEN }}

      - name: Deploy
        run: mvn -DskipTests -DuseGitHubPackages deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Deploy to Github
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
        if: always()


       
